remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: QMK Controller Comparison
description: A brief list of why you should just use STM32/RP2040
